services:
  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - ../.env
    volumes:
      - ./database/mongodb-data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - db-network

  adonisjs:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    ports:
      - "3001:3333"
    environment:
      IS_DOCKERIZED: true
    env_file:
      - ../.env
    restart: always
    depends_on:
      - mongo
    networks:
      - db-network

  nextjs:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
      args:
        API_BASE_URL: https://adonisjs.mcube.uk
        API_BASE_URL_SERVER: https://adonisjs.mcube.uk
    ports:
      - "3002:3333"
    env_file:
      - ../.env
    restart: always
    depends_on:
      - adonisjs
    networks:
      - db-network

  cloudflared_adonis:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN_ADONIS}
    networks: # This should be set to enable http://server:3000 as a URL
      - db-network

  cloudflared_next:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN_NEXT}
    networks: # This should be set to enable http://server:3000 as a URL
      - db-network

networks:
  db-network:
    driver: bridge
