- name: Configure fail2ban
  become: true
  blockinfile:
    path: /etc/fail2ban/jail.local
    block: |
      [DEFAULT]
      # the IP address range we want to ignore
      ignoreip = 127.0.0.1/8 

      # get email alerts
      action = %(action_)s
    create: true
  notify: Restart fail2ban

- name: Configure Fail2Ban SSH jail
  become: true
  blockinfile:
    path: /etc/fail2ban/jail.d/ssh.local
    block: |
      [sshd]
      enabled = true
      banaction = ufw
      port = {{ ssh_port }}
      filter = sshd
      logpath = %(sshd_log)s
      maxretry = 5
      bantime = 10m
    create: true
  notify: 
  - Restart fail2ban
  - Change shell to bash