// This file is auto-generated by @hey-api/openapi-ts

export type User = {
    id?: string;
    email: string;
    firstName: string;
    lastName: string;
    createdAt: string;
    updatedAt: string;
};

export type AuthForm = {
    email: string;
    password: string;
};

export type Success = {
    message: string;
};

export type _Error = {
    status: number;
    message: string;
    error: string;
};

export type AuthTokens = {
    accessToken: string;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Sends a list of users
     */
    200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostRegisterData = {
    body?: AuthForm;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * User already exists
     */
    409: _Error;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * Registration successful
     */
    200: Success;
};

export type PostRegisterResponse = PostRegisterResponses[keyof PostRegisterResponses];

export type PostLoginData = {
    body?: AuthForm;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginErrors = {
    /**
     * Invalid email or password
     */
    401: _Error;
};

export type PostLoginError = PostLoginErrors[keyof PostLoginErrors];

export type PostLoginResponses = {
    /**
     * Registration successful
     */
    200: AuthTokens;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutResponses = {
    /**
     * Logout successful
     */
    200: Success;
};

export type PostLogoutResponse = PostLogoutResponses[keyof PostLogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeResponses = {
    /**
     * Sends a list of users
     */
    200: User;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};