- name: Setup passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Ensure password authentication is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart SSH

- name: Check if 50-cloud-init.conf exists
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
  register: cloud_init_ssh_config_stat

- name: Ensure password authentication is disabled in 50-cloud-init.sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart SSH
  when: cloud_init_ssh_config_stat.stat.exists

- name: Disable root password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'