global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets: ['reverse-proxy:8080']
